{% set name = "types-redis" %}
{% set version = "4.6.0.20240409" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-redis-{{ version }}.tar.gz
  sha256: ce217c279581d769df992c5b76d61c65425b0a679626048e633e643868eb881b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/redis-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for redis
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
