{% set name = "types-redis" %}
{% set version = "4.6.0.20241004" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-redis-{{ version }}.tar.gz
  sha256: 5f17d2b3f9091ab75384153bfa276619ffa1cf6a38da60e10d5e6749cc5b902e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/redis-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for redis
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
